#pragma once

#define FRG_MOUSE_BUTTON_1         0
#define FRG_MOUSE_BUTTON_2         1
#define FRG_MOUSE_BUTTON_3         2
#define FRG_MOUSE_BUTTON_4         3
#define FRG_MOUSE_BUTTON_5         4
#define FRG_MOUSE_BUTTON_6         5
#define FRG_MOUSE_BUTTON_7         6
#define FRG_MOUSE_BUTTON_8         7
#define FRG_MOUSE_BUTTON_LAST      FRG_MOUSE_BUTTON_8
#define FRG_MOUSE_BUTTON_LEFT      FRG_MOUSE_BUTTON_1
#define FRG_MOUSE_BUTTON_RIGHT     FRG_MOUSE_BUTTON_2
#define FRG_MOUSE_BUTTON_MIDDLE    FRG_MOUSE_BUTTON_3